// IANA zone1970.tab entries tagged for Russia, grouped west-to-east by current UTC offset.
export const russianTimezoneOptions = [
  { value: "Europe/Kaliningrad", label: "UTC+02:00 — Калининград" },
  { value: "Europe/Moscow", label: "UTC+03:00 — Москва" },
  { value: "Europe/Simferopol", label: "UTC+03:00 — Симферополь" },
  { value: "Europe/Kirov", label: "UTC+03:00 — Киров" },
  { value: "Europe/Volgograd", label: "UTC+03:00 — Волгоград" },
  { value: "Europe/Astrakhan", label: "UTC+04:00 — Астрахань" },
  { value: "Europe/Saratov", label: "UTC+04:00 — Саратов" },
  { value: "Europe/Ulyanovsk", label: "UTC+04:00 — Ульяновск" },
  { value: "Europe/Samara", label: "UTC+04:00 — Самара, Удмуртия" },
  { value: "Asia/Yekaterinburg", label: "UTC+05:00 — Екатеринбург, Урал" },
  { value: "Asia/Omsk", label: "UTC+06:00 — Омск" },
  { value: "Asia/Novosibirsk", label: "UTC+07:00 — Новосибирск" },
  { value: "Asia/Barnaul", label: "UTC+07:00 — Барнаул, Алтай" },
  { value: "Asia/Tomsk", label: "UTC+07:00 — Томск" },
  { value: "Asia/Novokuznetsk", label: "UTC+07:00 — Новокузнецк, Кузбасс" },
  { value: "Asia/Krasnoyarsk", label: "UTC+07:00 — Красноярск" },
  { value: "Asia/Irkutsk", label: "UTC+08:00 — Иркутск, Бурятия" },
  { value: "Asia/Chita", label: "UTC+09:00 — Чита, Забайкалье" },
  { value: "Asia/Yakutsk", label: "UTC+09:00 — Якутск" },
  { value: "Asia/Khandyga", label: "UTC+09:00 — Хандыга" },
  { value: "Asia/Vladivostok", label: "UTC+10:00 — Владивосток" },
  { value: "Asia/Ust-Nera", label: "UTC+10:00 — Усть-Нера" },
  { value: "Asia/Magadan", label: "UTC+11:00 — Магадан" },
  { value: "Asia/Sakhalin", label: "UTC+11:00 — Сахалин" },
  { value: "Asia/Srednekolymsk", label: "UTC+11:00 — Среднеколымск" },
  { value: "Asia/Kamchatka", label: "UTC+12:00 — Камчатка" },
  { value: "Asia/Anadyr", label: "UTC+12:00 — Анадырь" },
] as const;
